# Generated by Django 4.2.28 on 2026-02-20 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom / Entreprise')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('service', models.CharField(choices=[('site_vitrine', 'Site vitrine'), ('site_ecommerce', 'Site e-commerce'), ('application_web', 'Application web'), ('application_mobile', 'Application mobile'), ('api_backend', 'API / Backend'), ('autre', 'Autre')], max_length=50, verbose_name='Service demande')),
                ('budget', models.CharField(choices=[('moins_150k', 'Moins de 150 000 FCFA'),('150k_300k',  '150 000 - 300 000 FCFA'),('300k_600k',  '300 000 - 600 000 FCFA'),('600k_1m',    '600 000 - 1 000 000 FCFA'),('plus_1m',    'Plus de 1 000 000 FCFA'),('a_discuter', 'A discuter'),], max_length=20, verbose_name='Budget')),
                ('message', models.TextField(verbose_name='Message / Description du projet')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('repondu', 'Repondu'), ('archive', 'Archive')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('note_interne', models.TextField(blank=True, verbose_name="Note interne (visible seulement dans l'admin)")),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('client', models.CharField(max_length=200, verbose_name="Client (ex: Restaurant Le Comptoir, ou 'Projet fictif')")),
                ('categorie', models.CharField(choices=[('site_web', 'Site Web'), ('ecommerce', 'E-commerce'), ('app_web', 'Application Web'), ('app_mobile', 'Application Mobile'), ('api', 'API / Backend'), ('design', 'UI/UX Design')], max_length=30, verbose_name='Categorie')),
                ('description', models.TextField(verbose_name='Description courte (affichee sur le site)')),
                ('detail', models.TextField(blank=True, verbose_name='Details complets (probleme, solution, resultat)')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image / screenshot")),
                ('url_live', models.URLField(blank=True, verbose_name='URL du site en ligne')),
                ('url_github', models.URLField(blank=True, verbose_name='URL GitHub (optionnel)')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies (separees par des virgules)')),
                ('est_en_avant', models.BooleanField(default=False, verbose_name="Mettre en avant sur la page d'accueil")),
                ('est_fictif', models.BooleanField(default=False, verbose_name='Projet fictif / demonstration')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de realisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet portfolio',
                'verbose_name_plural': 'Projets portfolio',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('emoji', models.CharField(default='🚀', max_length=5, verbose_name='Emoji')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('prix_min', models.PositiveIntegerField(verbose_name='Prix minimum (FCFA)')),
                ('prix_max', models.PositiveIntegerField(blank=True, null=True, verbose_name="Prix maximum (FCFA) - laisser vide si 'Sur devis'")),
                ('prix_label', models.CharField(blank=True, max_length=100, verbose_name="Label tarif perso (ex: 'Sur devis', '60000/mois') - remplace les prix si rempli")),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies (separees par des virgules)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Afficher ce service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('nom_de_famille', models.CharField(blank=True, max_length=100, verbose_name='Nom de famille (optionnel)')),
                ('role', models.CharField(choices=[('fullstack', 'Fullstack & Lead Dev'), ('frontend', 'Frontend & UI/UX'), ('backend', 'Backend & API'), ('mobile', 'Mobile & DevOps'), ('autre', 'Autre')], max_length=30, verbose_name='Role principal')),
                ('bio', models.TextField(verbose_name='Bio courte (1-2 phrases)')),
                ('initiale', models.CharField(max_length=2, verbose_name="Initiale sur l'avatar (ex: A)")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email pro')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='Profil GitHub')),
                ('competences', models.CharField(blank=True, max_length=300, verbose_name='Competences (separees par des virgules)')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL photo de profil')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='Membre active')),
            ],
            options={
                'verbose_name': "Membre de l'equipe",
                'verbose_name_plural': "Membres de l'equipe",
                'ordering': ['ordre', 'prenom'],
            },
        ),
    ]
