# Generated by Django 4.2.28 on 2026-02-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=200, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Details complets'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, verbose_name="URL de l'image"),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_github',
            field=models.URLField(blank=True, verbose_name='URL GitHub'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label tarif perso - remplace les prix si rempli'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix maximum (FCFA) - laisser vide si Sur devis'),
        ),
    ]
